#!/bin/bash

# Attention this file should be in your workspace.
# i.e. one folder higher than the application folders.

# set the mqsi environment
if [ -z "$MQSI_VERSION" ]; then
  source /opt/ibm/ace-11/server/bin/mqsiprofile
fi

# deploy the application bar
mqsibar -a /home/aceuser/src/simple-restful-helloworld-app.bar -w /home/aceuser/ace-server

runaceserver
